account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as av
from . import views

app_name = 'account'

urlpatterns = [
	url(r'login/$',av.LoginView.as_view(template_name='account/login.html'),name='login'),
	url(r'logout/$',av.LogoutView.as_view(),name='logout'),
	url(r'signup/$',views.SignUp.as_view(), name='signup')
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
	url(r'^$',views.ListGroups.as_view(),name='all'),
	url(r'^new/$',views.CreateGroup.as_view(), name='create'),
	url(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
	url(r'join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
	url(r'leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name = 'posts'

urlpatterns = [
	url(r'^$',views.PostList.as_view(),name='all'),
	url(r'new/$',views.CreatePost.as_view(),name='create'),
	url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
	url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
	url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Sociefy</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'socialmedia/css/a.css' %}">
	

</head>
<body >
	<nav class="navbar mynav" role='navigation' id="navbar">
		<div class="container">
			<a class="navbar-brand mynav" href="{% url 'home' %}">Sociefy</a>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li><a href="{% url 'posts:create' %}" class="head">Post</a></li>
					<li><a href="{% url 'groups:all' %}" class="head">Groups</a></li>
					<li><a href="{% url 'groups:create' %}" class="head">Create Group</a></li>
					<li><a href="{% url 'account:logout' %}" class="head">Log Out</a></li>
				{% else %}
					<li><a href="{% url 'groups:all' %}" class="head">Groups</a></li>
					<li><a href="{% url 'account:login' %}" class="head">Login</a></li>
					<li><a href="{% url 'account:signup' %}" class="head">Sign Up</a></li>
				{% endif %}

			</ul>
		</div>
		
	</nav>
	<div class="container mycontent">
		{% block content %}

		{% endblock %}
	</div>
</body>
	<!--<script type="text/javascript" src="{% static 'socialmedia/js/a.js' %}"></script>-->
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Welcome to Sociefy!</h1>
	<h2>A microblogging website</h2>
	<br><br>
	<p>Create groups and chat with like minded people!</p>
	<p>Created with love by Sounak Majumder, IIESTS</p>
{% endblock %}
	

templates/test.html
{% extends "base.html" %}
{% block content %}
	<h1>You are now logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
	<h1>Thanks for visiting</h1>
{% endblock %}